services:
  - type: web
    name: zyro-vouch-bot
    runtime: python
    pythonVersion: "3.12.3"
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
